apiVersion: mink.io.musil/v1
kind: Broker
metadata:
  labels:
    app.kubernetes.io/name: mink
    app.kubernetes.io/managed-by: kustomize
  name: broker-sample
spec:
  image: "ghcr.io/jmpargana/musil-server:0.1.5"
  replicas: 1
  storageSize: "1Gi"
  port: 9092
