name: Dependency Review

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  dependency-review:
    permissions:
      contents: read
    name: Review dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Dependency Review
        uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1
